package:
  name: conda-protect
  version: {{ GIT_DESCRIBE_TAG }}.{{ GIT_BUILD_STR }}

source:
  git_url: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=3.8.1,<4.0.0
    - conda >=23.7.0
    - rich
    - click

test:
  imports:
    - conda_protect
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/conda-incubator/conda-protect
  summary: Protect conda environments to avoid mistakenly modifying them
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - travishathaway
